image: node:16-buster

definitions:
  clone:
    depth: full

pipelines:
  branches:
    master:
      - step:
          name: Build & Push Docker Container(s)
          services:
            - docker
          caches:
            - docker
          script:
            - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            - docker build -t dep-check-pipeline .
            - docker tag dep-check-pipeline iagllctech//dep-check-pipeline:latest
            - docker tag dep-check-pipeline iagllctech//dep-check-pipeline:$(date '+%Y.%m.%d')
            - docker push iagllctech/dep-check-pipeline:latest
            - docker push iagllctech/dep-check-pipeline:$(date '+%Y.%m.%d')